### ISSUE TITLE
QA for  Contributor Comment Financial Incentives - On Issue

### ISSUE THREAD

**Issue by 0xcodercrane** [ubiquibot/staging#14]
QA for [Contributor Comment Financial Incentives - On Issue](https://github.com/ubiquity/ubiquibot/issues/272#top)

**Comment by Draeieg** [comment]
pasting random stuff to check

Bounty hunters can gain xp and level up, allowing them to complete higher priority bounties 

xp=dollars earned
if a bounty is performed perfectly the hunter will get a perfect "bonus" on his xp (maybe to the dollars too), this bonus can turn into a "streak" where each successive perfect bounty will grow the streak and as a result the bonus can grow too

this means hunters that complete many small tasks perfectly will get more rewards than hunters that only complete bigger bounties, while hunters can do that  this will numerically show the difference between those who read and work carefully, effectively "Gaming the system"

**Comment by 0xcodercrane** [comment]
Lets kick off testing since tomorrow @Draeieg  lol

**Comment by Draeieg** [comment]
> Lets kick off testing since tomorrow @Draeieg  lol

Alright, assigned you ok the other one cuz we don't pay the hunter(assignee) on comments

**Comment by 0xcodercrane** [comment]
Its getting handled by the config as of now

**Comment by 0xcodercrane** [comment]
> pasting random stuff to check
> 
> Bounty hunters can gain xp and level up, allowing them to complete higher priority bounties
> 
> xp=dollars earned if a bounty is performed perfectly the hunter will get a perfect "bonus" on his xp (maybe to the dollars too), this bonus can turn into a "streak" where each successive perfect bounty will grow the streak and as a result the bonus can grow too
> 
> this means hunters that complete many small tasks perfectly will get more rewards than hunters that only complete bigger bounties, while hunters can do that this will numerically show the difference between those who read and work carefully, effectively "Gaming the system"

Just testing here

**Comment by pavlovcik** [comment]
> pasting random stuff to check
> 
> Bounty hunters can gain xp and level up, allowing them to complete higher priority bounties
> 
> xp=dollars earned if a bounty is performed perfectly the hunter will get a perfect "bonus" on his xp (maybe to the dollars too), this bonus can turn into a "streak" where each successive perfect bounty will grow the streak and as a result the bonus can grow too
> 
> this means hunters that complete many small tasks perfectly will get more rewards than hunters that only complete bigger bounties, while hunters can do that this will numerically show the difference between those who read and work carefully, effectively "Gaming the system"

You could always do lorem ipsum too to make the intent of your comment clearer for quick review.
