### ISSUE TITLE
Verify the Bot's ability to automatically close stale pull requests 

### ISSUE THREAD

**Issue by pavlovcik** [ubiquibot/staging#41]
If a bounty hunter gets disqualified (unassigned) due to inactivity, their pull request should automatically be closed.

>> I thought the bot was able to handle this already?

> hard to say, we already have a task that might make the unassignment better  https://github.com/ubiquity/ubiquibot/issues/408

_Originally posted by @rndquu in https://github.com/ubiquity/ubiquity-dollar/issues/665#issuecomment-1597054088_

**Comment by pavlovcik** [comment]
That looks promising!

**Comment by pavlovcik** [comment]
> <table>
>   <tr>
>     <td style="border:1px solid"></td>
>     <td style="border:1px solid"></td>
>   </tr>
>   <tr>
>     <td style="border:1px solid">Deadline</td>
>     <td style="border:1px solid">Mon, 03 Jul 2023 20:26:35 GMT</td>
>   </tr>
>   <tr>
>     <td style="border:1px solid">Registered Wallet</td>
>     <td style="border:1px solid">0xb87d1713f2fade89fe9de557a2e37d10f006a5d1</td>
>   </tr>
>   <tr>
>     <td style="border:1px solid">Payment Multiplier</td>
>     <td style="border:1px solid">2.00</td>
>   </tr>
>   <tr>
>     <td style="border:1px solid">Multiplier Reason</td>
>     <td style="border:1px solid">testing </td>
>   </tr>
>   <tr>
>     <td style="border:1px solid">Total Bounty</td>
>     <td style="border:1px solid">25 USD</td>
>   </tr>
>   </table>

I just realized this was implemented with a mistake. It should all be in a monospace font.

**Comment by pavlovcik** [comment]
Why was this closed as not planned? Should we move it to a different repo?

**Comment by Draeieg** [comment]
> Why was this closed as not planned? Should we move it to a different repo?

Duplicate issue

**Comment by pavlovcik** [comment]
You should link the duplicate in a comment here and close as not planned.

**Comment by Draeieg** [comment]
QA done in [https://github.com/ubiquibot/staging/issues/38](38)
