### ISSUE TITLE
QA for Bounty fix reassign

### ISSUE THREAD

**Issue by Draeieg** [ubiquibot/staging#53]
Testing pr <a href="https://github.com/ubiquity/ubiquibot/pull/472">472</a>

**Comment by devpanther** [comment]
I noticed the bot goes dead sometimes even locally, it resounds to commands and then it doesn't anymore till I restart the server

Started recently @pavlovcik @0xcodercrane

**Comment by pavlovcik** [comment]
> I noticed the bot goes dead sometimes even locally, it responds to commands/add price and then it doesn't anymore till I restart the server
> 
> Started recently @pavlovcik @0xcodercrane 

This should be diagnosed. If I had more context I would write a bounty.

**Comment by devpanther** [comment]
@Draeieg how do we go about this QA?

**Comment by Draeieg** [comment]
ping

**Comment by Draeieg** [comment]
ping

**Comment by devpanther** [comment]
@Draeieg try reassign
