### ISSUE TITLE
QA for fix: regex too loose for commands

### ISSUE THREAD

**Issue by Draeieg** [ubiquibot/staging#55]
Testing pr <a href="https://github.com/ubiquity/ubiquibot/pull/480">480</a>

**Comment by devpanther** [comment]
> /help

**Comment by devpanther** [comment]
i want /help

**Comment by devpanther** [comment]
i need `/help`

**Comment by devpanther** [comment]
Please /assign me

**Comment by devpanther** [comment]
Please /unassign me

**Comment by devpanther** [comment]
@Draeieg

**Comment by Draeieg** [comment]
idhgiJDHFVJHOEJAG /wallet

**Comment by Draeieg** [comment]
user invokes /wallet command with their address as the argument (exactly as we do currently.)
the bot posts a link to pay.ubq.fi/verify?user=pavlovcik&wallet=0x4007CE2083c7F3E18097aeB3A39bb8eC149a341d
the dApp parses the URL parameters and then asks for a signature
upon success there must be some type of webhook interface to the bot (@0xcodercrane @rndquu I would like your input here)
The bot posts a wallet registration success comment on the issue.

**Comment by Draeieg** [comment]
you can jusy use /help

**Comment by Draeieg** [comment]
filler text wherever /multiplier @Draeieg 2
