### ISSUE TITLE
QA for self config syntax

### ISSUE THREAD

**Issue by me505** [ubiquibot/staging#61]
Testing pr [515](https://github.com/ubiquity/ubiquibot/pull/515)

**Comment by me505** [comment]
i am dumb

**Comment by me505** [comment]
@pavlovcik what should i do 
i have never done this before

**Comment by me505** [comment]
@Draeieg can you help me with this

**Comment by pavlovcik** [comment]
> Insufficient permissions to update the payout multiplier. You are not an `admin` or `billing_manager`

Let me try setting you as a `billing_manager` just give me a few minutes.

**Comment by me505** [comment]
thank you

**Comment by me505** [comment]
@pavlovcik

**Comment by me505** [comment]
@pavlovcik

**Comment by me505** [comment]
this comment says to check if the sender is a "admin" or "billing_manager" but you have a used a logical and [here](https://github.com/me505/ubiquibot/blob/dev-3/src/handlers/comment/handlers/multiplier.ts#L61C5-L61C5)

**Comment by me505** [comment]
hmmm...

**Comment by pavlovcik** [comment]
@0xcodercrane me505 is a billing manager I just checked on the settings. There seems to be an issue with the bot?

**Comment by me505** [comment]
yes it might be
https://github.com/ubiquibot/staging/issues/61#issuecomment-1637490337

**Comment by pavlovcik** [comment]
> this comment says to check if the sender is a "admin" or "billing_manager" but you have a used a logical and [here](https://github.com/me505/ubiquibot/blob/dev-3/src/handlers/comment/handlers/multiplier.ts#L61C5-L61C5)

You're not reading the code right. If you are not an admin or billing manager then read permissions from the database. However we should be able to set your permissions using a command I just realized. 

/help

**Comment by pavlovcik** [comment]
I really dislike these error messages

**Comment by pavlovcik** [comment]
I'm looking at the implementation here https://github.com/ubiquity/ubiquibot/pull/297/files and I can't figure it out.

**Comment by me505** [comment]
hmm

**Comment by me505** [comment]
wait the commit hasnt mergerd :skull:

**Comment by pavlovcik** [comment]
Make sure that only admins can set their own multiplier! Or else a bounty hunter could max out theirs I guess.
