### ISSUE TITLE
QA for font of the table

### ISSUE THREAD

**Issue by AnakinSkywalkeer** [ubiquibot/staging#74]
Testing pr [538](https://github.com/ubiquity/ubiquibot/pull/538)

**Comment by AnakinSkywalkeer** [comment]
how im supposed to add time labels

**Comment by AnakinSkywalkeer** [comment]
@pavlovcik can u help pls

**Comment by Draeieg** [comment]
> @pavlovcik can u help pls

please read the readme instructions for QA carefully, hunters QA their bounties it THEIR forked repos, not in our staging environment
